apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -sample

resources:
- ../base

images:
- name: quay.io/confidential-containers/reqs-payload
  newTag: latest
- name: quay.io/kata-containers/kata-deploy
  newName: quay.io/kata-containers/kata-deploy-ci
  newTag: kata-containers-latest

patches:
- patch: |-
    - op: replace
      path: /spec/config/runtimeClasses
      value:
      - name: "kata-clh"
        snapshotter: "nydus"
        pullType: ""
      - name: "kata-qemu"
        snapshotter: "nydus"
        pullType: ""
      - name: "kata-qemu-tdx"
        snapshotter: "nydus"
        pullType: ""
      - name: "kata-qemu-sev"
        snapshotter: "nydus"
        pullType: ""
      - name: "kata-qemu-snp"
        snapshotter: "nydus"
        pullType: ""
    - op: add
      path: /spec/config/defaultRuntimeClassName
      value: "kata-qemu"
    - op: add
      path: /spec/config/debug
      value: false
    - op: add
      path: /spec/config/environmentVariables
      value:
        # It means that we're relying on the cluster to already have
        # containerd v1.7+ running.  If you know for sure that's not
        # the case, please, set this variable to `true`
        - name: "INSTALL_OFFICIAL_CONTAINERD"
          value: "false"
  target:
    kind: CcRuntime
